### ISSUE TITLE
will add interface to ReinforcementLearning.jl ?

### ISSUE THREAD

**Issue by zdx3578** [biaslab/RxEnvironments.jl#34]
thanks for your Great job. 
add interface to ReinforcementLearning.jl will try more env, is there an access plan?

**Comment by wouterwln** [comment]
Hi, thanks for your comment. `RxEnvironments.jl` is designed with a different philosophy than `ReinforcementLearning.jl`. You can read more about this [here](https://biaslab.github.io/RxEnvironments.jl/dev/lib/philosophy/). The main point of making reactive environments is that reinforcement learning agents will break down because of the asynchronous nature of the environment. Therefore, there's no plans to add interfaces to `ReinforcementLearning.jl`
