### ISSUE TITLE
Example with categorical control space

### ISSUE THREAD

**Issue by kobus78** [biaslab/RxEnvironments.jl#63]
Not an issue as such, but just a reminder to provide us with an example that makes use of a categorical control space. For example, a 'windy grid' example (as is often encountered in the Reinforcement Learning literature). This will really be helpful as many of our problems do not use a continuous control space.

**Comment by kobus78** [comment]
Thanks again @wouterwln. Just for the record, here is a reference paper: https://arxiv.org/pdf/2108.12245

**Comment by kobus78** [comment]
I remember in yesterday's meeting you mentioned that (hope I understood this correctly) active inference does not happen yet in RxEnvironments - currently only MPC. When do you estimate that RxInfer will be tied in? I appreciate you taking care of this so quickly @wouterwln. Thanks again.

**Comment by wouterwln** [comment]
Yes, you're right, there's no AIF happening yet in any `RxEnvironments` demo. However, I have to emphasize that the inference process (whether it's AIF or MPC) is a task that should be delegated to `RxInfer`, and I'm not planning to incorporate this into `RxEnvironments`. There is an idea to make boilerplate code that links `RxInfer` with an environment defined in `RxEnvironments` (I like to coin `RxAgents` as the name of the "linking package" between the two), but the main thing is to get AIF happening in `RxInfer`, as its part of the inference procedure (I think Thijs' and Magnus' LAIF papers implement AIF in RxInfer, I definitely know that Magnus' dissertation is on how to put AIF on a factor graph, and by extension this would mean that you would be able to run AIF algorithms in `RxInfer`, because we use factor graphs under the hood.

I hope this story is clear, if not, I'd be happy to elaborate further :)
